services:
  rature-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BREVO_FORM_URL: ${VITE_BREVO_FORM_URL:-}
    container_name: rature
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.rature.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.rature.entrypoints=websecure
      - traefik.http.routers.rature.tls=true
      - traefik.http.routers.rature.tls.certresolver=mytlschallenge
      - traefik.http.routers.rature.middlewares=security-headers@file
      - traefik.http.routers.rature-http.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.rature-http.entrypoints=web
      - traefik.http.routers.rature-http.middlewares=redirect-to-https@docker
      - traefik.http.services.rature.loadbalancer.server.port=80

networks:
  traefik:
    external: true
